### ISSUE TITLE
Which Ada runtime profile ?

### ISSUE THREAD

**Issue by NicoPy** [simonjwright/cortex-gnat-rts#31]
Hi,

It is not clear to me which Ada runtime profile is generated when compiling this RTS.
Adacore bb-runtimes sources allow to generate zfp, Ravenscar-sfp and Ravenscar-full profiles runtimes.
I discovered that these profiles are very restrictive when tasking is involved (I'm new to Ada).
As FREE-RTOS is used under the hood, I wonder if full Ada is usable with this RTS or if there are restrictions.

Nicolas

**Comment by simonjwright** [comment]
On 5 Sep 2020, at 13:30, Nicolas Pinault <notifications@github.com> wrote:
> It is not clear to me which Ada runtime profile is generated when compiling this RTS.
> Adacore bb-runtimes sources allow to generate zfp, Ravenscar-sfp and Ravenscar-full profiles runtimes.
> I discovered that these profiles are very restrictive when tasking is involved (I'm new to Ada).
> As FREE-RTOS is used under the hood, I wonder if full Ada is usable with this RTS or if there are restrictions.
> 
I suppose there are two or three possible meanings of "profile" here.

First, the deeply technical as in ARM 13.12 Pragma Restrictions and Pragma Profile <http://www.ada-auth.org/standards/rm12_w_tc1/html/RM-13-12.html>,

"A pragma Restrictions expresses the user's intent to abide by certain restrictions. A pragma Profile expresses the user's intent to abide by a set of Restrictions or other specified run-time policies. These may facilitate the construction of simpler run-time environments."

Second, it could mean the set of facilities available to user software (e.g. does it support Ada.Numerics? Ada.Containers?)

All the RTSs we're thinking of here express the system-wide restrictions (sense 1) via pragmas at the head of package System. ZFP has the restriction No_Tasking. All the others have the Ravenscar profile <http://www.ada-auth.org/standards/rm12_w_tc1/html/RM-D-13.html> (the latest Full RTSs have GNAT_Extended_Ravenscar, now officially to be recognised as the Jorvik profile <http://www.ada-auth.org/standards/2xrm/html/RM-D-13.html> and available in GNAT CE), which as you say greatly restricts tasking.

My approach with Cortex GNAT RTS was to provide a runtime with the GCC Runtime Library exception <https://www.gnu.org/licenses/gcc-exception-3.1-faq.en.html>, to allow the production of proprietary software (other things being equal), which meant starting from the FSF compiler sources. Full tasking would have been needlessly challenging, so Ravenscar seemed a good approach (as adopted by AdaCore).

Since then, I've added non-tasking features, mostly in response to my own requirements, e.g. a small subset of Ada.Containers. See the list at the end of the README on Github <https://github.com/simonjwright/cortex-gnat-rts/blob/master/README.md>.

Aside from tasking limitations, AdaCore's FULL profiles include all of Ada.

**Comment by NicoPy** [comment]
My primary concern is about tasking. So I was thinking about zfp and  Ravenscar (Jorvik) profiles.
Since I'm tired of C flaws, I recently started to learn Ada. I use tasking a lot in my projects. The lack of tasking functionalities in zfp and Ravenscar profiles is a problem in the sense that it forces to write more  complex code (meaning more bug sources) to achieve the same goal.
Switching to Ada is a real learning effort. It is worse the effort only with some conditions. Easy tasking management  is a primary condition.

What I don't understand is the usefulness of FreeRTOS in your implementation. Doesn't the Ada FSF compiler sources implement tasking management (fully or partially)  ?

**Comment by simonjwright** [comment]
> On 6 Sep 2020, at 12:08, Nicolas Pinault <notifications@github.com> wrote:
> My primary concern is about tasking. So I was thinking about zfp and Ravenscar (Jorvik) profiles.
> Since I'm tired of C flaws, I recently started to learn Ada. I use tasking a lot in my projects. The lack of tasking functionalities in zfp and Ravenscar profiles is a problem in the sense that it forces to write more complex code (meaning more bug sources) to achieve the same goal.
> Switching to Ada is a real learning effort. It is worse the effort only with some conditions. Easy tasking management is a primary condition.
> 
I had one application where the limitations of Ravenscar tasking provided a useful brake on the rather lazy full-Ada approach I'd previously adopted. As it happened, Jorvik would have been even better (allowing more complex PO entry conditions).

When I was working, we used VxWorks on a VME PowerPC board with a gigabyte of RAM and a GHz clock, which had a full Ada implementation. But this was Ada95, so some of the more fancy recent "enhancements" weren't available.
> What I don't understand is the usefulness of FreeRTOS in your implementation. Doesn't the Ada FSF compiler sources implement tasking management (fully or partially) ?
> 
The FSF sources expect to run over an OS that provides pthreads, or equivalent. The tasking support in the AdaCore bare-board runtimes is bare metal, but I couldn't look at it (because I wanted to be able to apply the GCC Runtime Library exception); so I wanted a free RTOS, because what would be the advantage of rewriting all the low-level tasking support, for multiple architectures which I don't have access to?

With hindsight, I might have been able to retain a bit more of the AdaCore FSF implementation (they defer low-level stuff to System.OS_Interface, whereas I just called the FreeRTOS stuff directly via System.FreeRTOS.*).

**Comment by NicoPy** [comment]
> I had one application where the limitations of Ravenscar tasking provided a useful brake on the rather lazy full-Ada approach I'd previously adopted. As it happened, Jorvik would have been even better (allowing more complex PO entry conditions). When I was working, we used VxWorks on a VME PowerPC board with a gigabyte of RAM and a GHz clock, which had a full Ada implementation. But this was Ada95, so some of the more fancy recent "enhancements" weren't available.

I hope to use Ada at work some day. That's why I'm learning  Ada at home :)

> What I don't understand is the usefulness of FreeRTOS in your implementation. Doesn't the Ada FSF compiler sources implement tasking management (fully or partially) ?
> The FSF sources expect to run over an OS that provides pthreads, or equivalent. The tasking support in the AdaCore bare-board runtimes is bare metal, but I couldn't look at it (because I wanted to be able to apply the GCC Runtime Library exception); so I wanted a free RTOS, because what would be the advantage of rewriting all the low-level tasking support, for multiple architectures which I don't have access to? With hindsight, I might have been able to retain a bit more of the AdaCore FSF implementation (they defer low-level stuff to System.OS_Interface, whereas I just called the FreeRTOS stuff directly via System.FreeRTOS.*).

That's very interesting. I didn't know FSF relies on OS features. Replacing OS features with FreeRTOS ones is a clever hack.
Does this means it could be easy to add Ada _features_ like `select` ?

**Comment by simonjwright** [comment]
On 8 Sep 2020, at 10:55, Nicolas Pinault <notifications@github.com> wrote:
> 
> That's very interesting. I didn't know FSF relies on OS features. Replacing OS features with FreeRTOS ones is a clever hack.
> Does this means it could be easy to add Ada features like select ?

Sorry for late reply.

Adding e.g. select

**Comment by NicoPy** [comment]
@simonjwright It looks like your answer has been cut.

**Comment by simonjwright** [comment]
Sorry about that. Answer updated.

**Comment by NicoPy** [comment]
> Sorry about that. Answer updated.

No problem Simon.

> Adding e.g. select would mean having task entries, i.e. no longer a Ravenscar (or even Jorvik) profile. 

Yes, I know. That's what I want. Ravenscar/Jorvik profiles are too restrictive. I don't need to prove my programs, the systems I work on are not safety-critical.

> I dare say that it would be _possible_, 

Good to know :)

>but note that even AdaCore’s `-full-` runtimes are still Ravenscar.

I know. I ask them about that. The answer I got is the one I hoped. 
From my point of view, this is not the correct way to promote Ada as a language for everyone.

> Certainly not on my roadmap, I’m afraid.

OK. No problem. I'll try to use your work to do it myself.

Thanks for taking time to answer my questions.

**Comment by simonjwright** [comment]
I wrote up the process I used [on my blog](https://forward-in-code.blogspot.com/2015/06/building-runtime-system-for-arm-eabi.html). Good luck!

**Comment by NicoPy** [comment]
Thanks Simon.
